# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 0_Create Domains.py
# Created on: 2014-11-18 15:14:03.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
GDB_Rail_sde = "Database Connections\\GDB_Rail.sde"
ConsultantPM_txt = "V:\\Projects\\Specials\\Rail_Inventory_and_Condition\\_dev\\ProjectsWeb\\script\\ConsultantPM.txt"
VTransPM_txt = "V:\\Projects\\Specials\\Rail_Inventory_and_Condition\\_dev\\ProjectsWeb\\script\\VTransPM.txt"
Consultants_txt = "V:\\Projects\\Specials\\Rail_Inventory_and_Condition\\_dev\\ProjectsWeb\\script\\Consultants.txt"
ConsultantsContact_txt = "V:\\Projects\\Specials\\Rail_Inventory_and_Condition\\_dev\\ProjectsWeb\\script\\ConsultantsContact.txt"
ProjectType_txt = "V:\\Projects\\Specials\\Rail_Inventory_and_Condition\\_dev\\ProjectsWeb\\script\\ProjectType.txt"
LocationType_txt = "V:\\Projects\\Specials\\Rail_Inventory_and_Condition\\_dev\\ProjectsWeb\\script\\LocationType.txt"
VRLID-join_csv = "V:\\Projects\\Specials\\Rail_Inventory_and_Condition\\_dev\\ProjectsWeb\\script\\VRLID-join.csv"
AssetType_txt = "V:\\Projects\\Specials\\Rail_Inventory_and_Condition\\_dev\\ProjectsWeb\\script\\AssetType.txt"
AllPMs_txt = "V:\\Projects\\Specials\\Rail_Inventory_and_Condition\\_dev\\ProjectsWeb\\script\\AllPMs.txt"
ProjectDescription_txt = "V:\\Projects\\Specials\\Rail_Inventory_and_Condition\\_dev\\ProjectsWeb\\script\\ProjectDescription.txt"

# Process: Table To Domain
arcpy.TableToDomain_management(ConsultantPM_txt, "CODE", "DESCRIPTION", GDB_Rail_sde, "ConsultantPM", "Consultant Project Managers", "REPLACE")

# Process: Table To Domain (2)
arcpy.TableToDomain_management(VTransPM_txt, "CODE", "DESCRIPTION", GDB_Rail_sde, "VTransPM", "VTrans Project Managers", "REPLACE")

# Process: Table To Domain (3)
arcpy.TableToDomain_management(Consultants_txt, "CODE", "DESCRIPTION", GDB_Rail_sde, "Consultants", "Design Consultants", "REPLACE")

# Process: Table To Domain (4)
arcpy.TableToDomain_management(ConsultantsContact_txt, "CODE", "DESCRIPTION", GDB_Rail_sde, "ConsultantContact", "Consultant Contact Info", "REPLACE")

# Process: Table To Domain (5)
arcpy.TableToDomain_management(VRLID-join_csv, "RailLineCode", "RailLineDescription", GDB_Rail_sde, "RailLine", "Rail Line", "REPLACE")

# Process: Table To Domain (6)
arcpy.TableToDomain_management(AssetType_txt, "CODE", "DESCRIPTION", GDB_Rail_sde, "AssetType", "Asset Type", "REPLACE")

# Process: Table To Domain (7)
arcpy.TableToDomain_management(LocationType_txt, "CODE", "DESCRIPTION", GDB_Rail_sde, "LocType", "Project Location Type (Point, Line, Multi)", "REPLACE")

# Process: Table To Domain (9)
arcpy.TableToDomain_management(ProjectType_txt, "CODE", "DESCRIPTION", GDB_Rail_sde, "ProjectType", "Project Type", "REPLACE")

# Process: Table To Domain (10)
arcpy.TableToDomain_management(AllPMs_txt, "CODE", "DESCRIPTION", GDB_Rail_sde, "AllPMs", "All Project Managers", "REPLACE")

# Process: Table To Domain (8)
arcpy.TableToDomain_management(ProjectDescription_txt, "CODE", "DESCRIPTION", GDB_Rail_sde, "ProjDescript", "Basic Project Description", "REPLACE")

# Process: Sort Coded Value Domain
arcpy.SortCodedValueDomain_management(GDB_Rail_sde, "VTransPM", "CODE", "ASCENDING")

# Process: Sort Coded Value Domain (2)
arcpy.SortCodedValueDomain_management(GDB_Rail_sde, "Consultants", "CODE", "ASCENDING")

# Process: Sort Coded Value Domain (3)
arcpy.SortCodedValueDomain_management(GDB_Rail_sde, "ConsultantContact", "CODE", "ASCENDING")

# Process: Sort Coded Value Domain (4)
arcpy.SortCodedValueDomain_management(GDB_Rail_sde, "ProjectType", "CODE", "ASCENDING")

# Process: Sort Coded Value Domain (5)
arcpy.SortCodedValueDomain_management(GDB_Rail_sde, "RailLine", "CODE", "ASCENDING")

# Process: Sort Coded Value Domain (6)
arcpy.SortCodedValueDomain_management(GDB_Rail_sde, "AssetType", "CODE", "ASCENDING")

# Process: Sort Coded Value Domain (7)
arcpy.SortCodedValueDomain_management(GDB_Rail_sde, "AllPMs", "CODE", "ASCENDING")

# Process: Sort Coded Value Domain (8)
arcpy.SortCodedValueDomain_management(GDB_Rail_sde, "ProjDescript", "CODE", "ASCENDING")

# Process: Sort Coded Value Domain (9)
arcpy.SortCodedValueDomain_management(GDB_Rail_sde, "ConsultantPM", "CODE", "ASCENDING")

# Process: Sort Coded Value Domain (10)
arcpy.SortCodedValueDomain_management(GDB_Rail_sde, "LocType", "CODE", "ASCENDING")

