# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 1_Create WebFC and ProjectTable.py
# Created on: 2014-11-18 15:14:35.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
GDB_Rail_sde = "Database Connections\\GDB_Rail.sde"
Add_Project_WebFC = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
Project_Type = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
PIN = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
VTrans_PM = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
Consultant_PM = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
Consultant = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
Consultant_Contact = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
ToMP = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
Location_Type = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
Asset_Number = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
Basic_Project_Description = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
Full_Project_Description = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
Latest_Estimate = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
Env_All_Clear = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
Util_Clear = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
ROW_Clear = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
RR_Clear = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
Advertise_Target = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
AssetID = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
Rail_Line = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
FromMP = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
Asset_Type = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
Project_Name = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
Projects_Table = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Project_Type__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
PIN__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
VTrans_PM__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Consultant_PM__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Consultant__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Consultant_Contact__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
ToMP__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Location_Type__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Asset_Number__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Basic_Project_Description__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Full_Project_Description__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Latest_Estimate__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Env_All_Clear__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Util_Clear__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
ROW_Clear__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
RR_Clear__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Advertise_Target__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
AssetID__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Rail_Trail = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
FromMP__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Asset_Type__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Project_Name__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Line_Name = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Operator = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Rail_Line__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
VRLID = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Branch = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
State_Owned = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Division = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Subdivision = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Status_Update_WebFC = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdate_WebFC"
Action_Items = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdate_WebFC"
Latest_Estimate__3_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdate_WebFC"
Env_All_Clear__3_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdate_WebFC"
Util_Clear__3_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdate_WebFC"
ROW_Clear__3_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdate_WebFC"
RR_Clear__3_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdate_WebFC"
Advertise_Target__3_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdate_WebFC"
Project_Name__3_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdate_WebFC"
Status_Update = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdate_WebFC"
created_user = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
Include = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
last_edited_user = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
created_date = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
created_user__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdate_WebFC"
Updating_Project_Manager = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdate_WebFC"
last_edited_user__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdate_WebFC"
created_date__3_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdate_WebFC"
created_user__3_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Include__2_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
last_edited_user__3_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
created_date__5_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"

# Process: Create Feature Class
arcpy.CreateFeatureclass_management(GDB_Rail_sde, "PROJ_AddProject_WebFC", "POINT", "", "ENABLED", "DISABLED", "PROJCS['NAD_1983_StatePlane_Vermont_FIPS_4400',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-72.5],PARAMETER['Scale_Factor',0.9999642857142858],PARAMETER['Latitude_Of_Origin',42.5],UNIT['Meter',1.0]];-5123000 -14708800 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision", "", "0", "0", "0")

# Process: Add Field
arcpy.AddField_management(Add_Project_WebFC, "ProjectName", "TEXT", "", "", "100", "Project Name", "NULLABLE", "REQUIRED", "")

# Process: Add Field (23)
arcpy.AddField_management(Project_Name, "ProjectType", "TEXT", "", "", "", "", "NULLABLE", "REQUIRED", "ProjectType")

# Process: Add Field (2)
arcpy.AddField_management(Project_Type, "PIN", "TEXT", "", "", "7", "PIN Number", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (3)
arcpy.AddField_management(PIN, "VTransPM", "TEXT", "", "", "", "VTrans Project Manager", "NULLABLE", "REQUIRED", "VTransPM")

# Process: Add Field (4)
arcpy.AddField_management(VTrans_PM, "ConsultantPM", "TEXT", "", "", "", "Consultant Project Manager", "NULLABLE", "NON_REQUIRED", "ConsultantPM")

# Process: Add Field (5)
arcpy.AddField_management(Consultant_PM, "Consultant", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "Consultants")

# Process: Add Field (6)
arcpy.AddField_management(Consultant, "ConsultantPMContact", "TEXT", "", "", "250", "Consultant PM Contact Info", "NULLABLE", "NON_REQUIRED", "ConsultantContact")

# Process: Add Field (7)
arcpy.AddField_management(Consultant_Contact, "RailLine", "TEXT", "", "", "", "Rail Line", "NULLABLE", "REQUIRED", "RailLine")

# Process: Add Field (20)
arcpy.AddField_management(Rail_Line, "FromMP", "DOUBLE", "", "", "", "Starting Milepost", "NULLABLE", "REQUIRED", "")

# Process: Add Field (21)
arcpy.AddField_management(FromMP, "ToMP", "DOUBLE", "", "", "", "Ending Mile Post", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (8)
arcpy.AddField_management(ToMP, "AssetType", "TEXT", "", "", "", "Asset Type", "NULLABLE", "NON_REQUIRED", "AssetType")

# Process: Add Field (22)
arcpy.AddField_management(Asset_Type, "AssetID", "TEXT", "", "", "", "AssetID", "NULLABLE", "REQUIRED", "")

# Process: Add Field (19)
arcpy.AddField_management(AssetID, "LocationType", "TEXT", "", "", "", "Location Type", "NULLABLE", "NON_REQUIRED", "LocType")

# Process: Add Field (9)
arcpy.AddField_management(Location_Type, "AssetNumber", "TEXT", "", "", "", "Asset Number", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (10)
arcpy.AddField_management(Asset_Number, "BasicDescription", "TEXT", "", "", "250", "Basic Project Description", "NULLABLE", "NON_REQUIRED", "ProjDescript")

# Process: Add Field (11)
arcpy.AddField_management(Basic_Project_Description, "ProjectDescription", "TEXT", "", "", "500", "Full Project Description", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (12)
arcpy.AddField_management(Full_Project_Description, "LatestConstEst", "DOUBLE", "", "", "", "Latest Construction Estimate w/ E&C", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (13)
arcpy.AddField_management(Latest_Estimate, "EnvAllClear", "TEXT", "", "", "", "Environmental All Clear", "NULLABLE", "NON_REQUIRED", "Boolean")

# Process: Add Field (14)
arcpy.AddField_management(Env_All_Clear, "UtilClear", "TEXT", "", "", "", "Utilities Clearance", "NULLABLE", "NON_REQUIRED", "Boolean")

# Process: Add Field (15)
arcpy.AddField_management(Util_Clear, "ROWClear", "TEXT", "", "", "", "ROW Clearance", "NULLABLE", "NON_REQUIRED", "Boolean")

# Process: Add Field (16)
arcpy.AddField_management(ROW_Clear, "RRClear", "TEXT", "", "", "", "Railroad Clearance", "NULLABLE", "NON_REQUIRED", "Boolean")

# Process: Add Field (17)
arcpy.AddField_management(RR_Clear, "AdvertiseTarget", "TEXT", "", "", "", "Project Advertisement Target (Season/Year)", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (18)
arcpy.AddField_management(Advertise_Target, "Include", "TEXT", "", "", "", "Include In Reports", "NULLABLE", "NON_REQUIRED", "Boolean")

# Process: Add Field (59)
arcpy.AddField_management(Include, "created_user", "TEXT", "", "", "255", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (58)
arcpy.AddField_management(created_user, "created_date", "DATE", "", "", "255", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (61)
arcpy.AddField_management(created_date, "last_edited_user", "TEXT", "", "", "255", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (60)
arcpy.AddField_management(last_edited_user, "last_edited_date", "DATE", "", "", "255", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Create Feature Class (2)
arcpy.CreateFeatureclass_management(GDB_Rail_sde, "PROJ_StatusUpdate_WebFC", "POINT", "", "ENABLED", "DISABLED", "PROJCS['NAD_1983_StatePlane_Vermont_FIPS_4400',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-72.5],PARAMETER['Scale_Factor',0.9999642857142858],PARAMETER['Latitude_Of_Origin',42.5],UNIT['Meter',1.0]];-5123000 -14708800 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision", "", "0", "0", "0")

# Process: Add Field (55)
arcpy.AddField_management(Status_Update_WebFC, "ProjectName", "TEXT", "", "", "100", "Project Name", "NULLABLE", "REQUIRED", "ProjectName")

# Process: Add Field (56)
arcpy.AddField_management(Project_Name__3_, "Status", "TEXT", "", "", "255", "Status Update", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (57)
arcpy.AddField_management(Status_Update, "Action", "TEXT", "", "", "255", "Action Items", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (66)
arcpy.AddField_management(Action_Items, "LatestConstEst", "DOUBLE", "", "", "", "Latest Construction Estimate w/ E&C", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (67)
arcpy.AddField_management(Latest_Estimate__3_, "EnvAllClear", "TEXT", "", "", "", "Environmental All Clear", "NULLABLE", "NON_REQUIRED", "Boolean")

# Process: Add Field (68)
arcpy.AddField_management(Env_All_Clear__3_, "UtilClear", "TEXT", "", "", "", "Utilities Clearance", "NULLABLE", "NON_REQUIRED", "Boolean")

# Process: Add Field (69)
arcpy.AddField_management(Util_Clear__3_, "ROWClear", "TEXT", "", "", "", "ROW Clearance", "NULLABLE", "NON_REQUIRED", "Boolean")

# Process: Add Field (70)
arcpy.AddField_management(ROW_Clear__3_, "RRClear", "TEXT", "", "", "", "Railroad Clearance", "NULLABLE", "NON_REQUIRED", "Boolean")

# Process: Add Field (71)
arcpy.AddField_management(RR_Clear__3_, "AdvertiseTarget", "TEXT", "", "", "", "Project Advertisement Target", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (72)
arcpy.AddField_management(Advertise_Target__3_, "ProjectManager", "TEXT", "", "", "", "Updating Project Manager (Your Name)", "NULLABLE", "NON_REQUIRED", "AllPMs")

# Process: Add Field (63)
arcpy.AddField_management(Updating_Project_Manager, "created_user", "TEXT", "", "", "255", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (62)
arcpy.AddField_management(created_user__2_, "created_date", "DATE", "", "", "255", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (65)
arcpy.AddField_management(created_date__3_, "last_edited_user", "TEXT", "", "", "255", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (64)
arcpy.AddField_management(last_edited_user__2_, "last_edited_date", "DATE", "", "", "255", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Create Table
arcpy.CreateTable_management(GDB_Rail_sde, "PROJ_Projects", "", "")

# Process: Add Field (24)
arcpy.AddField_management(Projects_Table, "ProjectName", "TEXT", "", "", "100", "Project Name", "NULLABLE", "NON_REQUIRED", "ProjectType")

# Process: Add Field (46)
arcpy.AddField_management(Project_Name__2_, "ProjectType", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "ProjectType")

# Process: Add Field (25)
arcpy.AddField_management(Project_Type__2_, "PIN", "TEXT", "", "", "7", "PIN Number", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (26)
arcpy.AddField_management(PIN__2_, "VTransPM", "TEXT", "", "", "", "VTrans Project Manager", "NULLABLE", "NON_REQUIRED", "VTransPM")

# Process: Add Field (27)
arcpy.AddField_management(VTrans_PM__2_, "ConsultantPM", "TEXT", "", "", "", "Consultant Project Manager", "NULLABLE", "NON_REQUIRED", "ConsultantPM")

# Process: Add Field (28)
arcpy.AddField_management(Consultant_PM__2_, "Consultant", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "Consultants")

# Process: Add Field (29)
arcpy.AddField_management(Consultant__2_, "ConsultantPMContact", "TEXT", "", "", "250", "Consultant PM Contact Info", "NULLABLE", "NON_REQUIRED", "ConsultantContact")

# Process: Add Field (30)
arcpy.AddField_management(Consultant_Contact__2_, "RailLine", "TEXT", "", "", "", "Rail Line", "NULLABLE", "NON_REQUIRED", "RailLine")

# Process: Add Field (49)
arcpy.AddField_management(Rail_Line__2_, "VRLID", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (50)
arcpy.AddField_management(VRLID, "LineName", "TEXT", "", "", "", "Line Name", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (47)
arcpy.AddField_management(Line_Name, "Operator", "TEXT", "", "", "", "Operator", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (48)
arcpy.AddField_management(Operator, "Division", "TEXT", "", "", "", "Division", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (53)
arcpy.AddField_management(Division, "Subdivision", "TEXT", "", "", "", "Subdivision", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (54)
arcpy.AddField_management(Subdivision, "Branch", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (51)
arcpy.AddField_management(Branch, "StateOwned", "TEXT", "", "", "", "State Owned", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (52)
arcpy.AddField_management(State_Owned, "RailTrail", "TEXT", "", "", "", "Rail Trail", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (43)
arcpy.AddField_management(Rail_Trail, "FromMP", "DOUBLE", "", "", "", "FromMP", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (44)
arcpy.AddField_management(FromMP__2_, "ToMP", "DOUBLE", "", "", "", "ToMP", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (31)
arcpy.AddField_management(ToMP__2_, "AssetType", "TEXT", "", "", "", "Asset Type", "NULLABLE", "NON_REQUIRED", "AssetType")

# Process: Add Field (45)
arcpy.AddField_management(Asset_Type__2_, "AssetID", "TEXT", "", "", "", "AssetID", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (42)
arcpy.AddField_management(AssetID__2_, "LocationType", "TEXT", "", "", "", "Location Type", "NULLABLE", "NON_REQUIRED", "LocType")

# Process: Add Field (32)
arcpy.AddField_management(Location_Type__2_, "AssetNumber", "TEXT", "", "", "", "Asset Number", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (33)
arcpy.AddField_management(Asset_Number__2_, "BasicDescription", "TEXT", "", "", "250", "Basic Project Description", "NULLABLE", "NON_REQUIRED", "ProjDescript")

# Process: Add Field (34)
arcpy.AddField_management(Basic_Project_Description__2_, "ProjectDescription", "TEXT", "", "", "500", "Full Project Description", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (35)
arcpy.AddField_management(Full_Project_Description__2_, "LatestConstEst", "DOUBLE", "", "", "", "Latest Construction Estimate w/ E&C", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (36)
arcpy.AddField_management(Latest_Estimate__2_, "EnvAllClear", "TEXT", "", "", "", "Environmental All Clear", "NULLABLE", "NON_REQUIRED", "Boolean")

# Process: Add Field (37)
arcpy.AddField_management(Env_All_Clear__2_, "UtilClear", "TEXT", "", "", "", "Utilities Clearance", "NULLABLE", "NON_REQUIRED", "Boolean")

# Process: Add Field (38)
arcpy.AddField_management(Util_Clear__2_, "ROWClear", "TEXT", "", "", "", "ROW Clearance", "NULLABLE", "NON_REQUIRED", "Boolean")

# Process: Add Field (39)
arcpy.AddField_management(ROW_Clear__2_, "RRClear", "TEXT", "", "", "", "Railroad Clearance", "NULLABLE", "NON_REQUIRED", "Boolean")

# Process: Add Field (40)
arcpy.AddField_management(RR_Clear__2_, "AdvertiseTarget", "TEXT", "", "", "", "Project Advertisement Target", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (41)
arcpy.AddField_management(Advertise_Target__2_, "Include", "TEXT", "", "", "", "Include In Reports", "NULLABLE", "NON_REQUIRED", "Boolean")

# Process: Add Field (74)
arcpy.AddField_management(Include__2_, "created_user", "TEXT", "", "", "255", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (73)
arcpy.AddField_management(created_user__3_, "created_date", "DATE", "", "", "255", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (76)
arcpy.AddField_management(created_date__5_, "last_edited_user", "TEXT", "", "", "255", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (75)
arcpy.AddField_management(last_edited_user__3_, "last_edited_date", "DATE", "", "", "255", "", "NULLABLE", "NON_REQUIRED", "")

