# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 2_Create Status Update Table.py
# Created on: 2014-11-18 15:15:00.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
GDB_Rail_sde = "Database Connections\\GDB_Rail.sde"
Status_Update_WebFC = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdate_WebFC"
PROJ_Status_Updates__Table_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdates"
VRLID__4_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdates"
FromMP__4_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdates"

# Process: Create Table (2)
arcpy.CreateTable_management(GDB_Rail_sde, "PROJ_StatusUpdates", "'Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdate_WebFC'", "")

# Process: Add Field (77)
arcpy.AddField_management(PROJ_Status_Updates__Table_, "VRLID", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (78)
arcpy.AddField_management(VRLID__4_, "FromMP", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Field (79)
arcpy.AddField_management(FromMP__4_, "ToMP", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

