# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 5_Enable_Tracking_Versioned.py
# Created on: 2014-11-19 09:45:35.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
import arceditor


# Import arcpy module
import arcpy


# Local variables:
Projects_Table = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Status_Update_WebFC = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdate_WebFC"
Status_Update_Table = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdates"
Add_Project_WebFC = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"

# Process: Enable Editor Tracking
arcpy.EnableEditorTracking_management(Projects_Table, "created_user", "created_date", "last_edited_user", "last_edited_date", "", "UTC")

# Process: Enable Editor Tracking (2)
arcpy.EnableEditorTracking_management(Status_Update_WebFC, "created_user", "created_date", "last_edited_user", "last_edited_date", "", "UTC")

# Process: Enable Editor Tracking (3)
arcpy.EnableEditorTracking_management(Add_Project_WebFC, "created_user", "created_date", "last_edited_user", "last_edited_date", "", "UTC")

# Process: Enable Editor Tracking (4)
arcpy.EnableEditorTracking_management(Status_Update_Table, "created_user", "created_date", "last_edited_user", "last_edited_date", "", "UTC")

# Process: Register As Versioned
arcpy.RegisterAsVersioned_management(Projects_Table, "NO_EDITS_TO_BASE")

# Process: Register As Versioned (2)
arcpy.RegisterAsVersioned_management(Status_Update_WebFC, "NO_EDITS_TO_BASE")

# Process: Register As Versioned (3)
arcpy.RegisterAsVersioned_management(Status_Update_Table, "NO_EDITS_TO_BASE")

# Process: Register As Versioned (4)
arcpy.RegisterAsVersioned_management(Add_Project_WebFC, "NO_EDITS_TO_BASE")

