# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 8_StatusUpdate_Append.py
# Created on: 2014-11-19 09:47:08.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Status_Update_WebFC = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdate_WebFC"
Status_Updates__Table_ = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdates"
RAIL_ADMIN_PROJ_StatusUpdate = "RAIL_ADMIN.PROJ_StatusUpdate"

# Process: Status update web FC table view
arcpy.MakeTableView_management(Status_Update_WebFC, RAIL_ADMIN_PROJ_StatusUpdate, "", "", "OBJECTID OBJECTID VISIBLE NONE;Shape Shape VISIBLE NONE;ProjectName ProjectName VISIBLE NONE;Status Status VISIBLE NONE;Action Action VISIBLE NONE;LatestConstEst LatestConstEst VISIBLE NONE;EnvAllClear EnvAllClear VISIBLE NONE;UtilClear UtilClear VISIBLE NONE;ROWClear ROWClear VISIBLE NONE;RRClear RRClear VISIBLE NONE;AdvertiseTarget AdvertiseTarget VISIBLE NONE;ProjectManager ProjectManager VISIBLE NONE;created_user created_user VISIBLE NONE;created_date created_date VISIBLE NONE;last_edited_user last_edited_user VISIBLE NONE;last_edited_date last_edited_date VISIBLE NONE")

# Process: Append status web FC to status table
arcpy.Append_management("RAIL_ADMIN.PROJ_StatusUpdate", Status_Updates__Table_, "NO_TEST", "ProjectName \"Project Name\" true true true 100 Text 0 0 ,First,#,RAIL_ADMIN.PROJ_StatusUpdate,ProjectName,-1,-1;Status \"Status Update\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN.PROJ_StatusUpdate,Status,-1,-1;Action \"Action Items\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN.PROJ_StatusUpdate,Action,-1,-1;LatestConstEst \"Latest Construction Estimate w/ E&C\" true true false 8 Double 8 38 ,First,#,RAIL_ADMIN.PROJ_StatusUpdate,LatestConstEst,-1,-1;EnvAllClear \"Environmental All Clear\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN.PROJ_StatusUpdate,EnvAllClear,-1,-1;UtilClear \"Utilities Clearance\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN.PROJ_StatusUpdate,UtilClear,-1,-1;ROWClear \"ROW Clearance\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN.PROJ_StatusUpdate,ROWClear,-1,-1;RRClear \"Railroad Clearance\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN.PROJ_StatusUpdate,RRClear,-1,-1;AdvertiseTarget \"Project Advertisement Target\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN.PROJ_StatusUpdate,AdvertiseTarget,-1,-1;ProjectManager \"Updating Project Manager (Your Name)\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN.PROJ_StatusUpdate,ProjectManager,-1,-1;created_user \"created_user\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN.PROJ_StatusUpdate,created_user,-1,-1;created_date \"created_date\" true true false 36 Date 0 0 ,First,#,RAIL_ADMIN.PROJ_StatusUpdate,created_date,-1,-1;last_edited_user \"last_edited_user\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN.PROJ_StatusUpdate,last_edited_user,-1,-1;last_edited_date \"last_edited_date\" true true false 36 Date 0 0 ,First,#,RAIL_ADMIN.PROJ_StatusUpdate,last_edited_date,-1,-1;VRLID \"VRLID\" true true false 255 Text 0 0 ,First,#;FromMP \"FromMP\" true true false 8 Double 8 38 ,First,#;ToMP \"ToMP\" true true false 8 Double 8 38 ,First,#", "")

