# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 9_StatusUpdate_DynSeg.py
# Created on: 2014-11-19 09:47:37.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
GDB_Rail = "Database Connections\\GDB_Rail.sde"
Projects_Table = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
Rail_LRS = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.INV_Rail_LRS"
Stats_Update_Table = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdates"
RAIL_ADMIN_PROJ_StatusUpdate1 = "RAIL_ADMIN.PROJ_StatusUpdate1"
RAIL_ADMIN_PROJ_Projects_Vie3 = "RAIL_ADMIN.PROJ_Projects_Vie3"
RAIL_ADMIN_PROJ_StatusUpdate1__2_ = "RAIL_ADMIN.PROJ_StatusUpdate1"
VRLID = "RAIL_ADMIN.PROJ_StatusUpdate1"
FromMP = "RAIL_ADMIN.PROJ_StatusUpdate1"
Points = "RAIL_ADMIN.PROJ_StatusUpdate2"
Lines = "RAIL_ADMIN.PROJ_StatusUpdate3"
Point_Events = "RAIL_ADMIN Events"
Line_Events = "RAIL_ADMIN Events"

# Process: Make Table View (4)
arcpy.MakeTableView_management(Stats_Update_Table, RAIL_ADMIN_PROJ_StatusUpdate1, "", "", "OBJECTID OBJECTID VISIBLE NONE;ProjectName ProjectName VISIBLE NONE;Status Status VISIBLE NONE;Action Action VISIBLE NONE;LatestConstEst LatestConstEst VISIBLE NONE;EnvAllClear EnvAllClear VISIBLE NONE;UtilClear UtilClear VISIBLE NONE;ROWClear ROWClear VISIBLE NONE;RRClear RRClear VISIBLE NONE;AdvertiseTarget AdvertiseTarget VISIBLE NONE;ProjectManager ProjectManager VISIBLE NONE;created_user created_user VISIBLE NONE;created_date created_date VISIBLE NONE;last_edited_user last_edited_user VISIBLE NONE;last_edited_date last_edited_date VISIBLE NONE;VRLID VRLID VISIBLE NONE;FromMP FromMP VISIBLE NONE;ToMP ToMP VISIBLE NONE")

# Process: Make Table View (2)
arcpy.MakeTableView_management(Projects_Table, RAIL_ADMIN_PROJ_Projects_Vie3, "", "", "OBJECTID OBJECTID VISIBLE NONE;ProjectName ProjectName VISIBLE NONE;ProjectType ProjectType VISIBLE NONE;PIN PIN VISIBLE NONE;VTransPM VTransPM VISIBLE NONE;ConsultantPM ConsultantPM VISIBLE NONE;Consultant Consultant VISIBLE NONE;ConsultantPMContact ConsultantPMContact VISIBLE NONE;RailLine RailLine VISIBLE NONE;VRLID VRLID VISIBLE NONE;LineName LineName VISIBLE NONE;Operator Operator VISIBLE NONE;Division Division VISIBLE NONE;Subdivision Subdivision VISIBLE NONE;Branch Branch VISIBLE NONE;StateOwned StateOwned VISIBLE NONE;RailTrail RailTrail VISIBLE NONE;FromMP FromMP VISIBLE NONE;ToMP ToMP VISIBLE NONE;AssetType AssetType VISIBLE NONE;AssetID AssetID VISIBLE NONE;LocationType LocationType VISIBLE NONE;AssetNumber AssetNumber VISIBLE NONE;BasicDescription BasicDescription VISIBLE NONE;ProjectDescription ProjectDescription VISIBLE NONE;LatestConstEst LatestConstEst VISIBLE NONE;EnvAllClear EnvAllClear VISIBLE NONE;UtilClear UtilClear VISIBLE NONE;ROWClear ROWClear VISIBLE NONE;RRClear RRClear VISIBLE NONE;AdvertiseTarget AdvertiseTarget VISIBLE NONE;Include Include VISIBLE NONE;created_user created_user VISIBLE NONE;created_date created_date VISIBLE NONE;last_edited_user last_edited_user VISIBLE NONE;last_edited_date last_edited_date VISIBLE NONE")

# Process: Add Join
arcpy.AddJoin_management(RAIL_ADMIN_PROJ_StatusUpdate1, "ProjectName", RAIL_ADMIN_PROJ_Projects_Vie3, "ProjectName", "KEEP_COMMON")

# Process: Calculate Field
arcpy.CalculateField_management(RAIL_ADMIN_PROJ_StatusUpdate1__2_, "GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdates.VRLID", "[GDB_Rail.RAIL_ADMIN.PROJ_Projects.VRLID]", "VB", "")

# Process: Calculate Field (2)
arcpy.CalculateField_management(VRLID, "GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdates.FromMP", "[GDB_Rail.RAIL_ADMIN.PROJ_Projects.FromMP]", "VB", "")

# Process: Calculate Field (3)
arcpy.CalculateField_management(FromMP, "GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdates.ToMP", "[GDB_Rail.RAIL_ADMIN.PROJ_Projects.ToMP]", "VB", "")

# Process: Make Table View
arcpy.MakeTableView_management(Stats_Update_Table, Points, "ToMP is null", "", "OBJECTID OBJECTID VISIBLE NONE;ProjectName ProjectName VISIBLE NONE;Status Status VISIBLE NONE;Action Action VISIBLE NONE;LatestConstEst LatestConstEst VISIBLE NONE;EnvAllClear EnvAllClear VISIBLE NONE;UtilClear UtilClear VISIBLE NONE;ROWClear ROWClear VISIBLE NONE;RRClear RRClear VISIBLE NONE;AdvertiseTarget AdvertiseTarget VISIBLE NONE;ProjectManager ProjectManager VISIBLE NONE;created_user created_user VISIBLE NONE;created_date created_date VISIBLE NONE;last_edited_user last_edited_user VISIBLE NONE;last_edited_date last_edited_date VISIBLE NONE;VRLID VRLID VISIBLE NONE;FromMP FromMP VISIBLE NONE;ToMP ToMP VISIBLE NONE")

# Process: Make Route Event Layer
arcpy.MakeRouteEventLayer_lr(Rail_LRS, "VRLID", Points, "VRLID POINT FromMP", Point_Events, "", "NO_ERROR_FIELD", "NO_ANGLE_FIELD", "NORMAL", "ANGLE", "LEFT", "POINT")

# Process: Feature Class to Feature Class
arcpy.FeatureClassToFeatureClass_conversion(Point_Events, GDB_Rail, "PROJ_StatusPoints", "", "ProjectName \"Project Name\" true true true 100 Text 0 0 ,First,#,RAIL_ADMIN Events,ProjectName,-1,-1;Status \"Status Update\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN Events,Status,-1,-1;Action \"Action Items\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN Events,Action,-1,-1;LatestConstEst \"Latest Construction Estimate w/ E&C\" true true false 8 Double 8 38 ,First,#,RAIL_ADMIN Events,LatestConstEst,-1,-1;EnvAllClear \"Environmental All Clear\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN Events,EnvAllClear,-1,-1;UtilClear \"Utilities Clearance\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN Events,UtilClear,-1,-1;ROWClear \"ROW Clearance\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN Events,ROWClear,-1,-1;RRClear \"Railroad Clearance\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN Events,RRClear,-1,-1;AdvertiseTarget \"Project Advertisement Target\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN Events,AdvertiseTarget,-1,-1;ProjectManager \"Updating Project Manager (Your Name)\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN Events,ProjectManager,-1,-1;created_user \"created_user\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN Events,created_user,-1,-1;created_date \"created_date\" true true false 36 Date 0 0 ,First,#,RAIL_ADMIN Events,created_date,-1,-1;last_edited_user \"last_edited_user\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN Events,last_edited_user,-1,-1;last_edited_date \"last_edited_date\" true true false 36 Date 0 0 ,First,#,RAIL_ADMIN Events,last_edited_date,-1,-1;VRLID \"VRLID\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN Events,VRLID,-1,-1;FromMP \"FromMP\" true true false 8 Double 8 38 ,First,#,RAIL_ADMIN Events,FromMP,-1,-1;ToMP \"ToMP\" true true false 8 Double 8 38 ,First,#,RAIL_ADMIN Events,ToMP,-1,-1", "")

# Process: Make Table View (3)
arcpy.MakeTableView_management(Stats_Update_Table, Lines, "ToMP is not null", "", "OBJECTID OBJECTID VISIBLE NONE;ProjectName ProjectName VISIBLE NONE;Status Status VISIBLE NONE;Action Action VISIBLE NONE;LatestConstEst LatestConstEst VISIBLE NONE;EnvAllClear EnvAllClear VISIBLE NONE;UtilClear UtilClear VISIBLE NONE;ROWClear ROWClear VISIBLE NONE;RRClear RRClear VISIBLE NONE;AdvertiseTarget AdvertiseTarget VISIBLE NONE;ProjectManager ProjectManager VISIBLE NONE;created_user created_user VISIBLE NONE;created_date created_date VISIBLE NONE;last_edited_user last_edited_user VISIBLE NONE;last_edited_date last_edited_date VISIBLE NONE;VRLID VRLID VISIBLE NONE;FromMP FromMP VISIBLE NONE;ToMP ToMP VISIBLE NONE")

# Process: Make Route Event Layer (2)
arcpy.MakeRouteEventLayer_lr(Rail_LRS, "VRLID", Lines, "VRLID LINE FromMP ToMP", Line_Events, "", "NO_ERROR_FIELD", "NO_ANGLE_FIELD", "NORMAL", "ANGLE", "LEFT", "POINT")

# Process: Feature Class to Feature Class (2)
arcpy.FeatureClassToFeatureClass_conversion(Line_Events, GDB_Rail, "PROJ_StatusLines", "", "ProjectName \"Project Name\" true true true 100 Text 0 0 ,First,#,RAIL_ADMIN Events,ProjectName,-1,-1;Status \"Status Update\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN Events,Status,-1,-1;Action \"Action Items\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN Events,Action,-1,-1;LatestConstEst \"Latest Construction Estimate w/ E&C\" true true false 8 Double 8 38 ,First,#,RAIL_ADMIN Events,LatestConstEst,-1,-1;EnvAllClear \"Environmental All Clear\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN Events,EnvAllClear,-1,-1;UtilClear \"Utilities Clearance\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN Events,UtilClear,-1,-1;ROWClear \"ROW Clearance\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN Events,ROWClear,-1,-1;RRClear \"Railroad Clearance\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN Events,RRClear,-1,-1;AdvertiseTarget \"Project Advertisement Target\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN Events,AdvertiseTarget,-1,-1;ProjectManager \"Updating Project Manager (Your Name)\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN Events,ProjectManager,-1,-1;created_user \"created_user\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN Events,created_user,-1,-1;created_date \"created_date\" true true false 36 Date 0 0 ,First,#,RAIL_ADMIN Events,created_date,-1,-1;last_edited_user \"last_edited_user\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN Events,last_edited_user,-1,-1;last_edited_date \"last_edited_date\" true true false 36 Date 0 0 ,First,#,RAIL_ADMIN Events,last_edited_date,-1,-1;VRLID \"VRLID\" true true false 255 Text 0 0 ,First,#,RAIL_ADMIN Events,VRLID,-1,-1;FromMP \"FromMP\" true true false 8 Double 8 38 ,First,#,RAIL_ADMIN Events,FromMP,-1,-1;ToMP \"ToMP\" true true false 8 Double 8 38 ,First,#,RAIL_ADMIN Events,ToMP,-1,-1", "")

