# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# x_temp_linename_calc.py
# Created on: 2014-11-19 09:48:10.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
GDB_Rail_RAIL_ADMIN_PROJ_Projects = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
GDB_Rail_RAIL_ADMIN_INV_Rail_LRS = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.INV_Rail_LRS"
RAIL_ADMIN_PROJ_Projects_Vie = "RAIL_ADMIN.PROJ_Projects_Vie"
RAIL_ADMIN_PROJ_Projects_Vie__3_ = "RAIL_ADMIN.PROJ_Projects_Vie"

# Process: Make Table View
arcpy.MakeTableView_management(GDB_Rail_RAIL_ADMIN_PROJ_Projects, RAIL_ADMIN_PROJ_Projects_Vie, "", "", "OBJECTID OBJECTID VISIBLE NONE;ProjectName ProjectName VISIBLE NONE;ProjectType ProjectType VISIBLE NONE;PIN PIN VISIBLE NONE;VTransPM VTransPM VISIBLE NONE;ConsultantPM ConsultantPM VISIBLE NONE;Consultant Consultant VISIBLE NONE;ConsultantPMContact ConsultantPMContact VISIBLE NONE;RailLine RailLine VISIBLE NONE;VRLID VRLID VISIBLE NONE;LineName LineName VISIBLE NONE;Operator Operator VISIBLE NONE;Division Division VISIBLE NONE;Subdivision Subdivision VISIBLE NONE;Branch Branch VISIBLE NONE;StateOwned StateOwned VISIBLE NONE;RailTrail RailTrail VISIBLE NONE;FromMP FromMP VISIBLE NONE;ToMP ToMP VISIBLE NONE;AssetType AssetType VISIBLE NONE;AssetID AssetID VISIBLE NONE;LocationType LocationType VISIBLE NONE;AssetNumber AssetNumber VISIBLE NONE;BasicDescription BasicDescription VISIBLE NONE;ProjectDescription ProjectDescription VISIBLE NONE;LatestConstEst LatestConstEst VISIBLE NONE;EnvAllClear EnvAllClear VISIBLE NONE;UtilClear UtilClear VISIBLE NONE;ROWClear ROWClear VISIBLE NONE;RRClear RRClear VISIBLE NONE;AdvertiseTarget AdvertiseTarget VISIBLE NONE;Include Include VISIBLE NONE;created_user created_user VISIBLE NONE;created_date created_date VISIBLE NONE;last_edited_user last_edited_user VISIBLE NONE;last_edited_date last_edited_date VISIBLE NONE")

# Process: Add Join
arcpy.AddJoin_management(RAIL_ADMIN_PROJ_Projects_Vie, "VRLID", GDB_Rail_RAIL_ADMIN_INV_Rail_LRS, "VRLID", "KEEP_COMMON")

# Process: Calculate Field
arcpy.CalculateField_management(RAIL_ADMIN_PROJ_Projects_Vie__3_, "GDB_Rail.RAIL_ADMIN.PROJ_Projects.LineName", "[GDB_Rail.RAIL_ADMIN.INV_Rail_LRS.LineName]", "VB", "")

