# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# XXX_Delete_it_all.py
# Created on: 2014-11-19 09:48:33.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
PROJ_Lines = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Lines"
PROJ_Points = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Points"
PROJ_Projects_Table = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_Projects"
PROJ_Status_Points = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusPoints"
PROJ_Status_Update_Web_FC = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdate_WebFC"
PROJ_Status_Update_Table = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusUpdates"
PROJ_Add_Project_Web_FC = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_AddProject_WebFC"
GDB_Rail = "Database Connections\\GDB_Rail.sde"
PROJ_Status_Lines = "Database Connections\\GDB_Rail.sde\\GDB_Rail.RAIL_ADMIN.PROJ_StatusLines"

# Process: Delete (2)
arcpy.Delete_management(PROJ_Lines, "FeatureClass")

# Process: ConsultantPM
arcpy.DeleteDomain_management(GDB_Rail, "ConsultantPM")

# Process: VTransPM
arcpy.DeleteDomain_management(GDB_Rail, "VTransPM")

# Process: Consultants
arcpy.DeleteDomain_management(GDB_Rail, "Consultants")

# Process: ConsultantContact
arcpy.DeleteDomain_management(GDB_Rail, "ConsultantContact")

# Process: ProjectType
arcpy.DeleteDomain_management(GDB_Rail, "ProjectType")

# Process: LocType
arcpy.DeleteDomain_management(GDB_Rail, "LocType")

# Process: RailLine
arcpy.DeleteDomain_management(GDB_Rail, "RailLine")

# Process: AssetType
arcpy.DeleteDomain_management(GDB_Rail, "AssetType")

# Process: AllPMs
arcpy.DeleteDomain_management(GDB_Rail, "AllPMs")

# Process: ProjDescript
arcpy.DeleteDomain_management(GDB_Rail, "ProjDescript")

# Process: Delete (4)
arcpy.Delete_management(PROJ_Projects_Table, "Table")

# Process: Delete (6)
arcpy.Delete_management(PROJ_Status_Update_Web_FC, "FeatureClass")

# Process: Delete (7)
arcpy.Delete_management(PROJ_Status_Update_Table, "Table")

# Process: Delete (8)
arcpy.Delete_management(PROJ_Add_Project_Web_FC, "FeatureClass")

# Process: Delete (3)
arcpy.Delete_management(PROJ_Points, "FeatureClass")

# Process: Delete (5)
arcpy.Delete_management(PROJ_Status_Points, "FeatureClass")

# Process: Delete
arcpy.Delete_management(PROJ_Status_Lines, "FeatureClass")

